version: '3'
services:
    counter:
        build: .
        links:
            - redis
        ports:
            - "9090:5000"
        volumes:
            - ./:/app
    redis:
        image: redis:5-alpine

