version: '3'
services:
    counter:
        image: aleskandro/pycounter:latest
        restart: always
        links:
            - redis
        ports:
            - "9090:5000"
    redis:
        image: redis:5-alpine

