#apiVersion: v1
#kind: Service
#metadata:
#  name: order-service-db
#  namespace: spring-example-ecommerce-okd
#spec:
#  ports:
#    - port: 27017
#  selector:
#    app: order-service-db
#---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: spring-example-ecommerce-okd
spec:
  ports:
  - port: 8080
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-example-ecommerce-okd
  name: order-service
spec:
  selector:
      matchLabels:
          app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: docker-registry.default.svc:5000/spring-example-ecommerce-okd/order-service-prod:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: order-service-db
              key: database-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-service-db
              key: database-password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: order-service-db
              key: database-name
        - name: KAFKA_ADDRESS
          valueFrom:
              configMapKeyRef:
                name: order-service-env-file
                key: KAFKA_ADDRESS
        - name: KAFKA_GROUP_ID
          valueFrom:
              configMapKeyRef:
                name: order-service-env-file
                key: KAFKA_GROUP_ID
        - name: KAFKA_MAIN_TOPIC
          valueFrom:
              configMapKeyRef:
                name: order-service-env-file
                key: KAFKA_GROUP_ID
        - name: MONGODB_HOSTNAME
          valueFrom:
              configMapKeyRef:
                name: order-service-env-file
                key: MONGODB_HOSTNAME
        - name: MONGODB_PORT
          valueFrom:
              configMapKeyRef:
                name: order-service-env-file
                key: MONGODB_PORT        
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3


