apiVersion: v1
kind: Service
metadata:
  name: hello-node
  labels:
    svc: hello-node
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: hello-kubernetes-pods

