stages:
    - build
    - deploy

before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.madfarm.it:4567

build-staging:
    stage: build
    only:
        - staging
    tags:
        - docker-shell
    script:
        - rsync -avz ./ /var/docker-gitlab/sportibook
        - cd /var/docker-gitlab/sportibook
        - cd backend/
        - mkdir -p media
        - docker build -t gitlab.madfarm.it:4567/madfarm/isportbook/backend-staging:latest . -f Dockerfile.staging
        - cd ../frontend/
        - docker build -t gitlab.madfarm.it:4567/madfarm/isportbook/frontend-staging:latest . -f Dockerfile.staging
        - cd ../docker/proxy
        - docker build -t gitlab.madfarm.it:4567/madfarm/isportbook/proxy-staging:latest . -f Dockerfile.staging
        - cd ../mariadb
        - docker build -t gitlab.madfarm.it:4567/madfarm/isportbook/mariadb-staging:latest . -f Dockerfile
        - docker push gitlab.madfarm.it:4567/madfarm/isportbook/proxy-staging:latest
        - docker push gitlab.madfarm.it:4567/madfarm/isportbook/backend-staging:latest
        - docker push gitlab.madfarm.it:4567/madfarm/isportbook/frontend-staging:latest
        - docker push gitlab.madfarm.it:4567/madfarm/isportbook/mariadb-staging:latest

deploy-staging:
    stage: deploy
    only:
        - staging
    tags:
        - docker-shell
    script:
        - cd /var/docker-gitlab/sportibook
        - cd docker
        - docker-compose -f docker-compose.staging.yml up -d

build-production:
    stage: build
    only:
        - production
    tags:
        - docker-shell
    script:
        - rsync -avz ./ /var/docker-gitlab/sportibook-prod
        - cd /var/docker-gitlab/sportibook-prod
        - cd backend/
        - mkdir -p media
        - docker build -t gitlab.madfarm.it:4567/madfarm/isportbook/backend-production:latest -t gitlab.madfarm.it:4567/madfarm/isportbook/backend-production:$CI_COMMIT_SHA . -f Dockerfile.production
        - cd ../frontend/
        - docker build -t gitlab.madfarm.it:4567/madfarm/isportbook/frontend-production:latest -t gitlab.madfarm.it:4567/madfarm/isportbook/frontend-production:$CI_COMMIT_SHA . -f Dockerfile.production
        - cd ../docker/proxy
        - docker build -t gitlab.madfarm.it:4567/madfarm/isportbook/proxy-production:latest -t  gitlab.madfarm.it:4567/madfarm/isportbook/proxy-production:$CI_COMMIT_SHA . -f Dockerfile.production
        - cd ../mariadb
        - docker build -t gitlab.madfarm.it:4567/madfarm/isportbook/mariadb-production:latest -t gitlab.madfarm.it:4567/madfarm/isportbook/mariadb-production:$CI_COMMIT_SHA . -f Dockerfile
        - docker push gitlab.madfarm.it:4567/madfarm/isportbook/proxy-production:latest
        - docker push gitlab.madfarm.it:4567/madfarm/isportbook/backend-production:latest
        - docker push gitlab.madfarm.it:4567/madfarm/isportbook/frontend-production:latest
        - docker push gitlab.madfarm.it:4567/madfarm/isportbook/mariadb-production:latest
        - docker push gitlab.madfarm.it:4567/madfarm/isportbook/proxy-production:$CI_COMMIT_SHA
        - docker push gitlab.madfarm.it:4567/madfarm/isportbook/backend-production:$CI_COMMIT_SHA
        - docker push gitlab.madfarm.it:4567/madfarm/isportbook/frontend-production:$CI_COMMIT_SHA
        - docker push gitlab.madfarm.it:4567/madfarm/isportbook/mariadb-production:$CI_COMMIT_SHA

deploy-production:
    stage: deploy
    only:
        - production
    tags:
        - docker-shell
    script:
        - cd /var/docker-gitlab/sportibook-prod
        - cd docker
        - docker-compose -f docker-compose.production.yml up -d

