version: '3'

services:
    db:
        image: sportibook-mariadb-staging:latest # Use a docker registry TODO
        volumes:
            - mariadb-staging:/var/lib/mysql
        env_file:
            - .env.db.staging

    backend:
        image: sportibook-backend-staging:latest
        restart: always
        command: wait_and_start.sh
        volumes:
            - ../backend/media:/code/media
        depends_on:
            - db
        env_file: 
            - .env.backend.staging

    proxy:
        image: sportibook-proxy-staging:latest
        ports:
            - 8080:80
        environment:
            NGINX_PORT: 80
        restart: always
        links:
            - backend
            - frontend
        depends_on:
            - backend
            - frontend

    frontend:
        image: sportibook-frontend-staging:latest
        restart: always
        environment:
            NGINX_PORT: 80
volumes:
    mariadb-staging:
