version: '3'

services:
    db:
        image: sportibook-mariadb-production:latest
        volumes:
            - mariadb-production:/var/lib/mysql
        env_file: 
            - .env.db.production

    backend:
        image: sportibook-backend-production:latest
        restart: always
        command: wait_and_start.sh
        volumes:
            - ../backend/media:/code/media
        depends_on:
            - db
        env_file:
            - .env.backend.production

    proxy:
        image: sportibook-proxy-production:latest
        ports:
            - 9080:80
        environment:
            NGINX_PORT: 80
        restart: always
        links:
            - backend
            - frontend
        depends_on:
            - backend
            - frontend

    frontend:
        image: sportibook-frontend-production:latest
        restart: always
        environment:
            NGINX_PORT: 80
volumes:
    mariadb-production:
