version: '3'

services:
  db:
    build: ./mariadb
    volumes:
        - mariadb-dev:/var/lib/mysql
    env_file:
        - .env.db.dev
  backend:
    build: ../backend/
    restart: always
    command: wait_and_start.sh
    volumes:
      - ../backend/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: 
        - .env.backend.dev
  proxy:
    build: ./proxy
    ports:
        - 8080:80
    environment:
        NGINX_PORT: 80
    restart: always
    links:
        - backend

  frontend_dev:
    build: ../frontend
    ports:
        - 4200:4200
    volumes:
        - ../frontend:/code

volumes:
    mariadb-dev:
