apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
spec:
  selector:
    matchLabels:
        app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: pycounter
        image: pycounter:v1
        ports:
        - containerPort: 5000
        volumeMounts:
            - mountPath: /app
              name: code-volume
      volumes:
      - name: code-volume
        hostPath:
          path: /counter
          type: Directory


