apiVersion: v1
data:
  MONGO_INITDB_DATABASE: admin
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"user-service-db-env-file","creationTimestamp":null},"data":{"MONGO_INITDB_DATABASE":"admin"}}
  creationTimestamp: "2019-12-11T11:57:24Z"
  name: user-service-db-env-file
  namespace: default
  resourceVersion: "154526"
  selfLink: /api/v1/namespaces/default/configmaps/user-service-db-env-file
  uid: 3f12f92d-25a2-4c31-bc62-4b303b465220
